<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite 1" duration-ms="5071" started-at="2017-06-18T16:38:41Z" finished-at="2017-06-18T16:38:46Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="5071" started-at="2017-06-18T16:38:41Z" finished-at="2017-06-18T16:38:46Z">
      <class name="basicTests.FirstClass">
        <test-method status="PASS" signature="startWebDriver(java.lang.String, java.lang.String)[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="startWebDriver" is-config="true" duration-ms="5119" started-at="2017-06-18T22:08:36Z" finished-at="2017-06-18T22:08:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWebDriver -->
        <test-method status="PASS" signature="startClass()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="startClass" is-config="true" duration-ms="3" started-at="2017-06-18T22:08:41Z" finished-at="2017-06-18T22:08:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startClass -->
        <test-method status="PASS" signature="check()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="check" duration-ms="5033" started-at="2017-06-18T22:08:41Z" finished-at="2017-06-18T22:08:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check -->
        <test-method status="FAIL" signature="simpleTestFail()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="simpleTestFail" duration-ms="5" started-at="2017-06-18T22:08:46Z" finished-at="2017-06-18T22:08:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at enhancements.AssertLogger.AssertFalse(AssertLogger.java:26)
	at basicTests.FirstClass.simpleTestFail(FirstClass.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- simpleTestFail -->
        <test-method status="PASS" signature="simpleTestTrue()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="simpleTestTrue" duration-ms="1" started-at="2017-06-18T22:08:46Z" finished-at="2017-06-18T22:08:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- simpleTestTrue -->
        <test-method status="PASS" signature="endClass()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="endClass" is-config="true" duration-ms="1" started-at="2017-06-18T22:08:46Z" finished-at="2017-06-18T22:08:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endClass -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:basicTests.FirstClass@6cc4c815]" name="closeBrowser" is-config="true" duration-ms="284" started-at="2017-06-18T22:08:46Z" finished-at="2017-06-18T22:08:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- basicTests.FirstClass -->
    </test> <!-- Test 1 -->
  </suite> <!-- Suite 1 -->
</testng-results>
